// Package refgen turns the @ekkolyth/miso-content source files plus the command
// registry into the CLI embed copy and the docs reference pages.
package refgen

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/ekkolyth/miso/internal/cli"
)

// walks up from start to the directory whose package.json names "miso"
func RepoRoot(start string) (string, error) {
	dir, err := filepath.Abs(start)
	if err != nil {
		return "", err
	}
	for {
		data, readErr := os.ReadFile(filepath.Join(dir, "package.json"))
		if readErr == nil {
			var pkg struct {
				Name string `json:"name"`
			}
			if json.Unmarshal(data, &pkg) == nil && pkg.Name == "miso" {
				return dir, nil
			}
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("repo root not found above %s", start)
		}
		dir = parent
	}
}

// reads packages/content/commands/*.mdx into name→body
func LoadSourceBodies(root string) (map[string]string, error) {
	dir := filepath.Join(root, "packages", "content", "commands")
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", dir, err)
	}
	bodies := make(map[string]string)
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".mdx") {
			continue
		}
		data, err := os.ReadFile(filepath.Join(dir, entry.Name()))
		if err != nil {
			return nil, err
		}
		bodies[strings.TrimSuffix(entry.Name(), ".mdx")] = string(data)
	}
	return bodies, nil
}

// fails if the content file set differs from the builtin set
func CheckCorrespondence(bodies map[string]string) error {
	want := make(map[string]bool, len(cli.Builtins))
	for _, cmd := range cli.Builtins {
		want[cmd.Name] = true
		if _, ok := bodies[cmd.Name]; !ok {
			return fmt.Errorf("builtin %q has no content file", cmd.Name)
		}
	}
	for name := range bodies {
		if !want[name] {
			return fmt.Errorf("content file %q has no matching builtin", name)
		}
	}
	return nil
}

const generatedNote = "{/* GENERATED by `go generate ./...` in apps/miso — do not edit. Edit packages/content/commands/<name>.mdx and regenerate. */}"

func metaLine(cmd cli.Command) string {
	parts := []string{"**Summary:** " + cmd.Summary}
	if len(cmd.Aliases) > 0 {
		parts = append(parts, "**Aliases:** `"+strings.Join(cmd.Aliases, "`, `")+"`")
	}
	usage := "miso " + cmd.Name
	if cmd.Usage != "" {
		usage += " " + cmd.Usage
	}
	parts = append(parts, "**Usage:** `"+usage+"`")
	return strings.Join(parts, " · ")
}

// the aggregated command reference page
func CommandsDoc(bodies map[string]string) string {
	var out strings.Builder
	out.WriteString("---\ntitle: Commands\n---\n\n")
	out.WriteString(generatedNote + "\n\n")
	out.WriteString("# Commands\n\n")
	for _, cmd := range cli.Builtins {
		out.WriteString("## `miso " + cmd.Name + "`\n\n")
		out.WriteString(metaLine(cmd) + "\n\n")
		out.WriteString(strings.TrimSpace(bodies[cmd.Name]) + "\n\n")
	}
	return out.String()
}

// the reserved-keywords reference page
func ReservedKeywordsDoc() string {
	var out strings.Builder
	out.WriteString("---\ntitle: Reserved Keywords\n---\n\n")
	out.WriteString(generatedNote + "\n\n")
	out.WriteString("# Reserved Keywords\n\n")
	out.WriteString("These names are miso's built-in commands. Meta commands run before any project is loaded; the rest can be shadowed by a project script of the same name.\n\n")
	out.WriteString("| Command | Aliases | Pre-config | Summary |\n|---|---|---|---|\n")
	for _, cmd := range cli.Builtins {
		aliases := "—"
		if len(cmd.Aliases) > 0 {
			aliases = "`" + strings.Join(cmd.Aliases, "`, `") + "`"
		}
		pre := "no"
		if cmd.Meta {
			pre = "yes"
		}
		fmt.Fprintf(&out, "| `%s` | %s | %s | %s |\n", cmd.Name, aliases, pre, cmd.Summary)
	}
	return out.String()
}

// mirrors bodies into dir/<name>.mdx, removing any stale file left over
// from a renamed or deleted command
func WriteEmbedCopy(dir string, bodies map[string]string) error {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		return err
	}
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".mdx") {
			continue
		}
		name := strings.TrimSuffix(entry.Name(), ".mdx")
		if _, ok := bodies[name]; !ok {
			if err := os.Remove(filepath.Join(dir, entry.Name())); err != nil {
				return err
			}
		}
	}
	for name, body := range bodies {
		if err := os.WriteFile(filepath.Join(dir, name+".mdx"), []byte(body), 0o644); err != nil {
			return err
		}
	}
	return nil
}
