package env

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/charmbracelet/log"
	"github.com/joho/godotenv"

	"github.com/ekkolyth/miso/internal/config"
	"github.com/ekkolyth/miso/internal/workspace"
)

// GenerateOptions toggles the populate/override layers on top of the keys-only template.
type GenerateOptions struct {
	Populate bool
	Override bool
}

// ParseGenerateFlags reads the tokens after `miso env`. -p/-o require -g.
func ParseGenerateFlags(args []string) (bool, GenerateOptions, error) {
	var generate bool
	var opts GenerateOptions
	for _, arg := range args {
		switch arg {
		case "-g", "--generate":
			generate = true
		case "-p", "--populate":
			opts.Populate = true
		case "-o", "--override":
			opts.Override = true
		default:
			return false, GenerateOptions{}, fmt.Errorf("unknown env flag: %s", arg)
		}
	}
	if (opts.Populate || opts.Override) && !generate {
		return false, GenerateOptions{}, errors.New("-p/--populate and -o/--override require -g/--generate")
	}
	return generate, opts, nil
}

// variableKeys returns the declared variable names for an entry (array preserved, object unordered).
func variableKeys(vars config.EnvVariables) []string {
	if len(vars.Array) > 0 {
		return append([]string(nil), vars.Array...)
	}
	keys := make([]string, 0, len(vars.Object))
	for name := range vars.Object {
		keys = append(keys, name)
	}
	return keys
}

// renderEnvFile emits a header then sorted KEY=value lines.
func renderEnvFile(keys []string, values map[string]string) string {
	var out strings.Builder
	out.WriteString("# generated by miso env --generate\n")
	for _, key := range keys {
		out.WriteString(key)
		out.WriteString("=")
		out.WriteString(values[key])
		out.WriteString("\n")
	}
	return out.String()
}

// readEnvSoft returns an empty map for a missing file; parse errors on an existing file surface.
func readEnvSoft(path string) (map[string]string, error) {
	if _, err := os.Stat(path); err != nil {
		if os.IsNotExist(err) {
			return map[string]string{}, nil
		}
		return nil, err
	}
	return godotenv.Read(path)
}

// scopeDir resolves a scope to the directory its .env.generated is written in:
// "global" is the repo root; any other scope is that member's directory.
func scopeDir(scope, projectRoot string, members []workspace.Member) (string, error) {
	if scope == "global" {
		return projectRoot, nil
	}
	member, err := workspace.Find(scope, members, projectRoot)
	if err != nil {
		return "", err
	}
	return member.Dir, nil
}

// scopedEntry pairs an env entry with the directory its path/override resolve from.
type scopedEntry struct {
	entry   *config.EnvEntry
	baseDir string
}

// collectScopes groups declared entries by scope. Root entries use their declared
// scope and resolve paths from the repo root; member-local entries take the
// member's name as scope and resolve from the member dir.
func collectScopes(projectRoot string, cfg config.Config, members []workspace.Member) map[string][]scopedEntry {
	scopes := map[string][]scopedEntry{}
	for _, entry := range cfg.Env {
		if entry.Scope == "" {
			continue
		}
		scopes[entry.Scope] = append(scopes[entry.Scope], scopedEntry{entry: entry, baseDir: projectRoot})
	}
	for _, member := range members {
		if member.ConfigPath == "" {
			continue
		}
		memberCfg, err := config.Load(member.Dir)
		if err != nil {
			continue
		}
		for _, entry := range memberCfg.Env {
			scopes[member.Name] = append(scopes[member.Name], scopedEntry{entry: entry, baseDir: member.Dir})
		}
	}
	return scopes
}

// buildScopeEnv returns the sorted declared key set and a values map for a scope:
// empty values for keys-only, baseline values with -p, override values winning with -o.
func buildScopeEnv(entries []scopedEntry, opts GenerateOptions) ([]string, map[string]string, error) {
	keySet := map[string]bool{}
	for _, scoped := range entries {
		for _, key := range variableKeys(scoped.entry.Variables) {
			keySet[key] = true
		}
	}
	keys := make([]string, 0, len(keySet))
	for key := range keySet {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	values := make(map[string]string, len(keys))
	for _, key := range keys {
		values[key] = ""
	}

	layer := func(source func(scopedEntry) string) error {
		for _, scoped := range entries {
			rel := source(scoped)
			if rel == "" {
				continue
			}
			found, err := readEnvSoft(filepath.Join(scoped.baseDir, rel))
			if err != nil {
				return err
			}
			for _, key := range keys {
				if val, ok := found[key]; ok {
					values[key] = val
				}
			}
		}
		return nil
	}

	if opts.Populate {
		if err := layer(func(scoped scopedEntry) string { return scoped.entry.Path }); err != nil {
			return nil, nil, err
		}
	}
	if opts.Override {
		if err := layer(func(scoped scopedEntry) string { return scoped.entry.Override }); err != nil {
			return nil, nil, err
		}
	}
	return keys, values, nil
}

// declarations below are wired into Generate/Command in a later task.
var (
	_ = collectScopes
	_ = log.Default
)
