package env

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/charmbracelet/log"
	"github.com/joho/godotenv"

	"github.com/ekkolyth/miso/internal/config"
	"github.com/ekkolyth/miso/internal/workspace"
)

// GenerateOptions toggles the populate/override layers on top of the keys-only template.
type GenerateOptions struct {
	Populate bool
	Override bool
}

// ParseGenerateFlags reads the tokens after `miso env`. -p/-o require -g.
func ParseGenerateFlags(args []string) (bool, GenerateOptions, error) {
	var generate bool
	var opts GenerateOptions
	for _, arg := range args {
		switch arg {
		case "-g", "--generate":
			generate = true
		case "-p", "--populate":
			opts.Populate = true
		case "-o", "--override":
			opts.Override = true
		default:
			return false, GenerateOptions{}, fmt.Errorf("unknown env flag: %s", arg)
		}
	}
	if (opts.Populate || opts.Override) && !generate {
		return false, GenerateOptions{}, errors.New("-p/--populate and -o/--override require -g/--generate")
	}
	return generate, opts, nil
}

// variableKeys returns the declared variable names for an entry (array preserved, object unordered).
func variableKeys(vars config.EnvVariables) []string {
	if len(vars.Array) > 0 {
		return append([]string(nil), vars.Array...)
	}
	keys := make([]string, 0, len(vars.Object))
	for name := range vars.Object {
		keys = append(keys, name)
	}
	return keys
}

// renderEnvFile emits a header then sorted KEY=value lines.
func renderEnvFile(keys []string, values map[string]string) string {
	var out strings.Builder
	out.WriteString("# generated by miso env --generate\n")
	for _, key := range keys {
		out.WriteString(key)
		out.WriteString("=")
		out.WriteString(values[key])
		out.WriteString("\n")
	}
	return out.String()
}

// readEnvSoft returns an empty map for a missing file; parse errors on an existing file surface.
func readEnvSoft(path string) (map[string]string, error) {
	if _, err := os.Stat(path); err != nil {
		if os.IsNotExist(err) {
			return map[string]string{}, nil
		}
		return nil, err
	}
	return godotenv.Read(path)
}

// declarations below are added in later tasks: scopeDir, collectScopes,
// buildScopeEnv, validateEntryValues, Generate, Command.
var (
	_ = sort.Strings
	_ = filepath.Join
	_ = log.Default
	_ = workspace.DiscoverMembers
)
