package env

import (
	"os"
	"path/filepath"
	"reflect"
	"testing"

	"github.com/charmbracelet/log"

	"github.com/ekkolyth/miso/internal/config"
	"github.com/ekkolyth/miso/internal/workspace"
)

func TestParseGenerateFlags(t *testing.T) {
	gen, opts, err := ParseGenerateFlags([]string{"-g", "--populate", "-o"})
	if err != nil {
		t.Fatalf("err: %v", err)
	}
	if !gen || !opts.Populate || !opts.Override {
		t.Errorf("got gen=%v %+v, want all true", gen, opts)
	}

	if _, _, err := ParseGenerateFlags([]string{"--populate"}); err == nil {
		t.Error("expected error: -p without -g")
	}
	if _, _, err := ParseGenerateFlags([]string{"--bogus"}); err == nil {
		t.Error("expected error: unknown flag")
	}
	if gen, _, err := ParseGenerateFlags([]string{}); err != nil || gen {
		t.Errorf("no flags => gen=false nil, got gen=%v err=%v", gen, err)
	}
}

func TestVariableKeys(t *testing.T) {
	arr := variableKeys(config.EnvVariables{Array: []string{"B", "A"}})
	if !reflect.DeepEqual(arr, []string{"B", "A"}) {
		t.Errorf("array keys = %v", arr)
	}
	obj := variableKeys(config.EnvVariables{Object: map[string]config.VarConfigOrString{"X": {}, "Y": {}}})
	if len(obj) != 2 {
		t.Errorf("object keys = %v, want 2", obj)
	}
}

func TestRenderEnvFile(t *testing.T) {
	out := renderEnvFile([]string{"A", "B"}, map[string]string{"A": "1", "B": ""})
	want := "# generated by miso env --generate\nA=1\nB=\n"
	if out != want {
		t.Errorf("render =\n%q\nwant\n%q", out, want)
	}
}

func TestReadEnvSoft_Missing(t *testing.T) {
	m, err := readEnvSoft(filepath.Join(t.TempDir(), "nope.env"))
	if err != nil || len(m) != 0 {
		t.Errorf("missing file => empty map, nil; got %v %v", m, err)
	}
}

func TestReadEnvSoft_Reads(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, ".env")
	if err := os.WriteFile(path, []byte("K=v\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	m, err := readEnvSoft(path)
	if err != nil || m["K"] != "v" {
		t.Errorf("read => K=v; got %v %v", m, err)
	}
}

func TestScopeDir(t *testing.T) {
	root := "/repo"
	members := []workspace.Member{{Name: "web", Dir: "/repo/apps/web"}}

	if dir, err := scopeDir("global", root, members); err != nil || dir != root {
		t.Errorf("global => %q %v, want %q", dir, err, root)
	}
	if dir, err := scopeDir("web", root, members); err != nil || dir != "/repo/apps/web" {
		t.Errorf("web => %q %v", dir, err)
	}
	if _, err := scopeDir("nope", root, members); err == nil {
		t.Error("unknown scope should error")
	}
}

func TestBuildScopeEnv_KeysOnly(t *testing.T) {
	entries := []scopedEntry{{entry: &config.EnvEntry{Variables: config.EnvVariables{Array: []string{"API_URL", "PORT"}}}, baseDir: t.TempDir()}}
	keys, values, err := buildScopeEnv(entries, GenerateOptions{})
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(keys, []string{"API_URL", "PORT"}) {
		t.Errorf("keys = %v (want sorted union)", keys)
	}
	if values["API_URL"] != "" || values["PORT"] != "" {
		t.Errorf("keys-only must have empty values, got %v", values)
	}
}

func TestBuildScopeEnv_PopulateThenOverride(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, ".env.local"), "API_URL=http://local\nPORT=3000\n")
	writeFile(t, filepath.Join(dir, ".env.infra"), "API_URL=http://prod\n")
	entries := []scopedEntry{{
		entry: &config.EnvEntry{
			Path:      ".env.local",
			Override:  ".env.infra",
			Variables: config.EnvVariables{Array: []string{"API_URL", "PORT"}},
		},
		baseDir: dir,
	}}
	_, values, err := buildScopeEnv(entries, GenerateOptions{Populate: true, Override: true})
	if err != nil {
		t.Fatal(err)
	}
	if values["API_URL"] != "http://prod" { // override wins
		t.Errorf("API_URL = %q, want override http://prod", values["API_URL"])
	}
	if values["PORT"] != "3000" { // populate only
		t.Errorf("PORT = %q, want 3000", values["PORT"])
	}
}

// writeFile is a tiny helper for these tests.
func writeFile(t *testing.T, path, body string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
}

func TestGenerate_KeysOnly_WritesTemplate(t *testing.T) {
	root := t.TempDir()
	cfg := config.Config{Repo: "miso", Env: []*config.EnvEntry{
		{Scope: "global", Variables: config.EnvVariables{Array: []string{"TOKEN", "PORT"}}},
	}}
	if err := Generate(root, cfg, log.New(os.Stderr), GenerateOptions{}); err != nil {
		t.Fatalf("generate: %v", err)
	}
	got, err := os.ReadFile(filepath.Join(root, ".env.generated"))
	if err != nil {
		t.Fatal(err)
	}
	want := "# generated by miso env --generate\nPORT=\nTOKEN=\n"
	if string(got) != want {
		t.Errorf("file =\n%q\nwant\n%q", got, want)
	}
}

func TestCommand_NoFlags_Validates(t *testing.T) {
	// No env config => Run's discovery mode; a lone .env makes it succeed.
	root := t.TempDir()
	writeFile(t, filepath.Join(root, ".env"), "X=1\n")
	if err := Command(root, config.Config{Repo: "miso"}, log.New(os.Stderr), nil); err != nil {
		t.Fatalf("command (validate) err: %v", err)
	}
}
