package env

import (
	"os"
	"path/filepath"
	"reflect"
	"testing"

	"github.com/ekkolyth/miso/internal/config"
	"github.com/ekkolyth/miso/internal/workspace"
)

func TestParseGenerateFlags(t *testing.T) {
	gen, opts, err := ParseGenerateFlags([]string{"-g", "--populate", "-o"})
	if err != nil {
		t.Fatalf("err: %v", err)
	}
	if !gen || !opts.Populate || !opts.Override {
		t.Errorf("got gen=%v %+v, want all true", gen, opts)
	}

	if _, _, err := ParseGenerateFlags([]string{"--populate"}); err == nil {
		t.Error("expected error: -p without -g")
	}
	if _, _, err := ParseGenerateFlags([]string{"--bogus"}); err == nil {
		t.Error("expected error: unknown flag")
	}
	if gen, _, err := ParseGenerateFlags([]string{}); err != nil || gen {
		t.Errorf("no flags => gen=false nil, got gen=%v err=%v", gen, err)
	}
}

func TestVariableKeys(t *testing.T) {
	arr := variableKeys(config.EnvVariables{Array: []string{"B", "A"}})
	if !reflect.DeepEqual(arr, []string{"B", "A"}) {
		t.Errorf("array keys = %v", arr)
	}
	obj := variableKeys(config.EnvVariables{Object: map[string]config.VarConfigOrString{"X": {}, "Y": {}}})
	if len(obj) != 2 {
		t.Errorf("object keys = %v, want 2", obj)
	}
}

func TestRenderEnvFile(t *testing.T) {
	out := renderEnvFile([]string{"A", "B"}, map[string]string{"A": "1", "B": ""})
	want := "# generated by miso env --generate\nA=1\nB=\n"
	if out != want {
		t.Errorf("render =\n%q\nwant\n%q", out, want)
	}
}

func TestReadEnvSoft_Missing(t *testing.T) {
	m, err := readEnvSoft(filepath.Join(t.TempDir(), "nope.env"))
	if err != nil || len(m) != 0 {
		t.Errorf("missing file => empty map, nil; got %v %v", m, err)
	}
}

func TestReadEnvSoft_Reads(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, ".env")
	if err := os.WriteFile(path, []byte("K=v\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	m, err := readEnvSoft(path)
	if err != nil || m["K"] != "v" {
		t.Errorf("read => K=v; got %v %v", m, err)
	}
}

func TestScopeDir(t *testing.T) {
	root := "/repo"
	members := []workspace.Member{{Name: "web", Dir: "/repo/apps/web"}}

	if dir, err := scopeDir("global", root, members); err != nil || dir != root {
		t.Errorf("global => %q %v, want %q", dir, err, root)
	}
	if dir, err := scopeDir("web", root, members); err != nil || dir != "/repo/apps/web" {
		t.Errorf("web => %q %v", dir, err)
	}
	if _, err := scopeDir("nope", root, members); err == nil {
		t.Error("unknown scope should error")
	}
}
